# Generated by Django 3.2.6 on 2022-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Поставки',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_column='номер_заказа')),
                ('amount_dol', models.DecimalField(db_column='стоимость_$', decimal_places=2, max_digits=10)),
                ('amount_rub', models.DecimalField(db_column='стоимость_руб', decimal_places=2, max_digits=10)),
                ('delivery', models.DateField(db_column='срок_поставки')),
            ],
            options={
                'db_table': 'Поставки',
            },
        ),
    ]
